### PR TITLE
Fix GCC 13.3 build on Ubuntu 22.04 when OpenCL bakecnd is enabled .

### PR DESCRIPTION
**Pull request by mwlasiuk**
This PR fixes build using GCC version 13.3 on Ubuntu 22.04 when OpenCL backend is enabled.

``` bash
/home/michal/code/nntrainer/nntrainer/layers/cl_layers/concat_cl.cpp:381:5: error: variable ‘input2_batch_size’ set but not used [-Werror=unused-but-set-variable]
  381 |     input2_batch_size, input2_height, input2_width, input2_channels;
      |     ^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

Unused __input2_batch_size__ could be removed but I would imagine it might be nice to inspect it using debugger.

**Self evaluation:**
1. Build test: [*]Passed [ ]Failed [ ]Skipped
2. Run test: [ ]Passed [ ]Failed [*]Skipped

**How to evaluate:**
Checkout on this PR branch on Ubuntu 22.04 machine and try building project using gcc version 13.3 compiler. Now build should succeed.

### CODE REVIEW

**Comment by mwlasiuk** [comment]
NOTE: PR created second time as I failed to properly sign off commit.

**Review by skykongkong8 — APPROVED** [review]

File: nntrainer/layers/cl_layers/concat_cl.cpp [hunk 1]
```diff
@@ -376,20 +376,17 @@ void ConcatLayerCl::incremental_forwarding(RunLayerContext &context,
 
 void ConcatLayerCl::ConcatProcess(Tensor const &in1, Tensor const &in2,
```
Comment (SeoHyungjun) [inline nntrainer/layers/cl_layers/concat_cl.cpp:377]: What do you think about changing `in1 and in2` to `input1 and input2`? 
The variables below are used as `input1_*` or `input2_*`. 
It would be better to unify the naming for consistency.

**Review by SeoHyungjun — APPROVED** [review]

File: nntrainer/layers/cl_layers/concat_cl.cpp (hunk 1 above)
Comment (mwlasiuk) [reply nntrainer/layers/cl_layers/concat_cl.cpp]: Good idea. Changed naming according to suggestion.

**Review by DonghakPark — APPROVED** [review]
1. Please Fill commit message Body 
2. Please Rebase , not merge commit ( we manage our commit history with rebase )

LGTM

**Review by jijoongmoon — APPROVED** [review]
LGTM
